version: '3.3'
services:
  admin:
    build: .
    container_name: admin
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    command: python3 ./run.py
    env_file:
      - .env

  db:
    image: postgres:13-alpine
    
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data: