version: '3.3'
services:
  web:
    build: ./app
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    # env_file:
    #   - ./.env
    # depends_on:
    #   - db

#   db:
#     image: postgres:13-alpine
#     environment:
#       - POSTGRES_DB=${POSTGRES_DB}
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_PASSWORD=${POSTGRES_PASS}
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/


# volumes:
#   postgres_data: