version: '3.3'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    ports:
      - "5432:5432"
    volumes:
      - ./psql_data:/var/lib/postgresql/data/
